### PR TITLE
Blog: Add Devise

### PR DESCRIPTION
**Pull request by Munsa1**
### In the following milestone I:
- [Install and setup devise](https://github.com/heartcombo/devise#getting-started).
- Register a new user.
- User logs in with a combination of email and password.
- Hashed password should be stored in the database.
- Ask for confirmation of email.
- Can reset password.

[Modify the views in devise](https://github.com/heartcombo/devise#configuring-views) for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A)[](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md#need-a-big-picture) and styling.

### CODE REVIEW

**Review by t-yanick — CHANGES_REQUESTED** [review]
Hi @Munsa1, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

### Please I will leave the comments here, since you did not make any changes to these files in this particular milestone ###
- [ ] Please make sure views in devise for the registration and login pages are modified to match the [wireframes ](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md) and their styling.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Munsa1** [comment]
> Hi @Munsa1,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes 
> _Check the comments under the review._
> 
> ### Please I will leave the comments here, since you did not make any changes to these files in this particular milestone
> * [ ]  Please make sure views in devise for the registration and login pages are modified to match the [wireframes ](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md) and their styling.
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

All requirements have been resolved

**Comment by Munsa1** [comment]
Requirements for styling have been resolved.
** Kindly note that this is a resubmission from last week**
[Link to the initial pull request](https://github.com/Munsa1/blog-app/pull/8)

**Review by MahmoudBakr23 — APPROVED** [review]
Hi @Munsa1 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
